apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: prd-monitoring
spec:
  values:
    grafana:
      persistence:
        enabled: true
        type: pvc
        storageClassName: standard
        size: 2Gi
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 100m
          memory: 128Mi
      grafana.ini:
        server:
          domain: localhost
          root_url: http://localhost:3000
        security:
          admin_user: admin
        auth:
          disable_login_form: false
          disable_signout_menu: false
        auth.anonymous:
          enabled: false
        users:
          allow_sign_up: false
          allow_org_create: false
      # Use an existing Kubernetes Secret for admin credentials to avoid
      # committing passwords into Git. The secret `grafana-admin-credentials`
      # must contain keys `admin-user` and `admin-password`.
      admin:
        existingSecret: grafana-admin-credentials
      # Mount provisioning configmaps so Grafana reads folder definitions
      extraConfigmapMounts:
        - name: mscqa-grafana-folders
          mountPath: /etc/grafana/provisioning/folders
        - name: mscqa-grafana-folder-permissions
          mountPath: /etc/grafana/provisioning/permissions
        - name: mscqa-teams
          mountPath: /etc/grafana/provisioning/teams
    prometheus:
      prometheusSpec:
        retention: 7d
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: standard
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 5Gi
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            cpu: 200m
            memory: 1Gi